
baseURL                        = 'https://rvspoc.org/'
languageCode                   = 'zh-CN'
title                          = 'RISC-V 软件移植及优化锦标赛'
theme                          = 'ananke'
paginate                       = 10
timeZone                       = "Asia/Shanghai"
pluralizeListTitles            = false
defaultContentLanguage         = 'zh'
defaultContentLanguageInSubdir = false

#
# Uncomment the below configuration if a common/fallback featured image is
# necessary, the image should be copied to the 'static/images/' directory.
#[cascade]
#  featured_image = 'images/<the-name>.jpg'
#

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Although it shows "unsafe", for this project anyone with document
      # editing privileges also has configuration file editing privileges, so
      # just pay more attention to the html code in the markdown. This will help
      # you to customise the style of the article to a greater extent.
      unsafe = true

[params]
  author = ''

  # Please uncomment and set the below registration_url on the eve of Dec 1st,
  # it's the switch to enable the registration link on the homepage.
  #registration_url = ''

  mainSections = ['posts']
  recent_posts_number = 10
  background_color_class = 'bg-orange'
  custom_css = ["cus_page.scss", "cus_site.scss"]
  [[params.ananke_socials]]
    name = 'github'
    url = 'https://github.com/plctlab/rvspoc'

[permalinks]
  [permalinks.page]
    posts = '/:slug/'
    challenges = '/:slug/'
  [permalinks.section]
    posts = '/posts/'
    challenges = '/challenges/'

[languages]
  [languages.zh]
    contentDir = 'content/zh'
    disabled = false
    languageCode = 'zh-CN'
    languageDirection = 'ltr'
    languageName = '简体中文'
    title = 'RISC-V 软件移植及优化锦标赛'
    weight = 1
    hasCJKLanguage = true
    summaryLength = 230
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'RISC-V Software Porting and Optimization Championship'
    weight = 2
  [languages.ru]
    contentDir = 'content/ru'
    disabled = false
    languageCode = 'ru-RU'
    languageDirection = 'ltr'
    languageName = 'Русский'
    title = 'Чемпионат по портированию и оптимизации программного обеспечения RISC-V'
    weight = 3
  [languages.ja]
    contentDir = 'content/ja'
    disabled = false
    languageCode = 'ja-JP'
    languageDirection = 'ltr'
    languageName = '日本語'
    title = 'RISC-V ソフトウェアの移植と最適化チャンピオンシップ'
    weight = 4
    hasCJKLanguage = true
    summaryLength = 230
  [languages.ko]
    contentDir = 'content/ko'
    disabled = false
    languageCode = 'ko-KR'
    languageDirection = 'ltr'
    languageName = '한국어'
    title = 'RISC-V 소프트웨어포팅및최적화챔피언십'
    weight = 5
    hasCJKLanguage = true
    summaryLength = 230
